# Generated by Django 3.2.13 on 2022-11-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0006_auto_20191215_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_address_ar',
            field=models.CharField(max_length=255, unique=True, verbose_name='Footer Arab Address'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_address_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='Footer Address'),
        ),
    ]
