# Generated by Django 3.2.13 on 2022-11-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0015_auto_20221108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_message',
            field=models.CharField(max_length=250, verbose_name='Email Message'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email Title'),
        ),
    ]
