# Generated by Django 3.2.13 on 2023-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0016_auto_20221110_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_message',
            field=models.CharField(max_length=2048, verbose_name='Email Message'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Email Title'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='description',
            field=models.CharField(max_length=2500, verbose_name='Progress Description'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='original_filename_path',
            field=models.CharField(default='', max_length=2500, verbose_name='Original Filename Path'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='temporary_filename_path',
            field=models.CharField(default='', max_length=2500, verbose_name='Temporary Filename Path'),
        ),
    ]
